# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='favorites', to='belt_app.Quote'),
        ),
    ]
